import 'package:flutter/services.dart';
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:prep_tracker/core/services/export_service.dart';
import 'package:prep_tracker/features/analytics/data/models/analytics_data_model.dart';
import 'package:prep_tracker/features/analytics/data/models/consistency_score_model.dart';
import 'package:prep_tracker/features/analytics/data/models/achievement_model.dart';

/// ── Analytics PDF Report Service ──
/// Builds a clean multi-page PDF report covering Overview, Consistency Score, Study, Gym, and Achievements.
class AnalyticsPdfService {
  static Future<void> generateAndDownloadPdfReport({
    required String userName,
    required AnalyticsDataModel data,
    required ConsistencyScoreModel scoreModel,
    required List<AchievementModel> achievements,
    required AnalyticsDateFilter dateFilter,
  }) async {
    final pdf = pw.Document();
    final dateFormat = DateFormat('MMMM dd, yyyy');
    final dateStr = dateFormat.format(DateTime.now());

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        header: (context) => pw.Container(
          alignment: pw.Alignment.centerRight,
          margin: const pw.EdgeInsets.only(bottom: 20),
          padding: const pw.EdgeInsets.only(bottom: 5),
          decoration: const pw.BoxDecoration(
            border: pw.Border(bottom: pw.BorderSide(color: PdfColors.grey300, width: 1)),
          ),
          child: pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text(
                'PREPTRACKER BY YASH — Performance Report',
                style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10, color: PdfColors.blue900),
              ),
              pw.Text(
                dateStr,
                style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700),
              ),
            ],
          ),
        ),
        footer: (context) => pw.Container(
          alignment: pw.Alignment.center,
          margin: const pw.EdgeInsets.only(top: 20),
          child: pw.Text(
            'Page ${context.pageNumber} of ${context.pagesCount}  •  Generated by PrepTracker By Yash',
            style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
          ),
        ),
        build: (context) => [
          // Header Banner
          pw.Container(
            padding: const pw.EdgeInsets.all(16),
            decoration: pw.BoxDecoration(
              color: PdfColors.blue800,
              borderRadius: pw.BorderRadius.circular(8),
            ),
            child: pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text(
                      'PREPTRACKER ANALYTICS REPORT',
                      style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold, color: PdfColors.white),
                    ),
                    pw.SizedBox(height: 4),
                    pw.Text(
                      'Student / User: $userName',
                      style: const pw.TextStyle(fontSize: 11, color: PdfColors.white),
                    ),
                    pw.Text(
                      'Date Range Filter: ${dateFilter.label}',
                      style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey300),
                    ),
                  ],
                ),
                pw.Container(
                  padding: const pw.EdgeInsets.symmetric(horizontal: 12, vertical: 8),
                  decoration: pw.BoxDecoration(
                    color: PdfColors.amber400,
                    borderRadius: pw.BorderRadius.circular(6),
                  ),
                  child: pw.Column(
                    children: [
                      pw.Text(
                        'SCORE',
                        style: pw.TextStyle(fontSize: 8, fontWeight: pw.FontWeight.bold, color: PdfColors.black),
                      ),
                      pw.Text(
                        '${scoreModel.currentScore}',
                        style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold, color: PdfColors.black),
                      ),
                      pw.Text(
                        scoreModel.level.label,
                        style: pw.TextStyle(fontSize: 7, fontWeight: pw.FontWeight.bold, color: PdfColors.black),
                      ),
                    ],
                  ),
                ),
              ],
            ),
          ),

          pw.SizedBox(height: 20),

          // Overview Statistics Table
          pw.Text('1. Executive Overview Statistics', style: pw.TextStyle(fontSize: 13, fontWeight: pw.FontWeight.bold, color: PdfColors.blue900)),
          pw.SizedBox(height: 8),
          pw.TableHelper.fromTextArray(
            border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.5),
            headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 9, color: PdfColors.white),
            headerDecoration: const pw.BoxDecoration(color: PdfColors.blue900),
            rowDecoration: const pw.BoxDecoration(color: PdfColors.grey100),
            cellAlignment: pw.Alignment.centerLeft,
            cellStyle: const pw.TextStyle(fontSize: 9),
            headers: ['Metric Name', 'Recorded Value'],
            data: [
              ['Total Study Hours Logged', '${data.totalStudyHours.toStringAsFixed(1)} hrs'],
              ['Today Study Time', '${data.todayStudyHours.toStringAsFixed(1)} hrs'],
              ['This Week Study Time', '${data.thisWeekStudyHours.toStringAsFixed(1)} hrs'],
              ['This Month Study Time', '${data.thisMonthStudyHours.toStringAsFixed(1)} hrs'],
              ['Total Study Sessions Logged', '${data.totalStudySessions} sessions'],
              ['Average Session Duration', '${data.avgSessionMinutes.toStringAsFixed(0)} mins'],
              ['Longest Study Session', '${data.longestSessionMinutes.toStringAsFixed(0)} mins'],
              ['Current Study Streak', '${data.currentStudyStreak} Days'],
              ['Longest Study Streak', '${data.longestStudyStreak} Days'],
              ['Total Subjects Tracked', '${data.totalSubjects}'],
              ['Completed / Pending Chapters', '${data.completedChaptersCount} completed / ${data.pendingChaptersCount} pending'],
              ['Revision Completion Rate', '${data.revisionCompletionPercentage.toStringAsFixed(1)}%'],
              ['Gym Attendance Rate', '${data.gymAttendancePercentage.toStringAsFixed(1)}% (${data.gymPresentDays} Days Present)'],
              ['Current Gym Streak', '${data.currentGymStreak} Days'],
              ['Consistency Score Rating', '${scoreModel.currentScore} / 900 (${scoreModel.level.label})'],
            ],
          ),

          pw.SizedBox(height: 20),

          // Consistency Score Breakdown
          pw.Text('2. Consistency Score Breakdown (300-900 Scale)', style: pw.TextStyle(fontSize: 13, fontWeight: pw.FontWeight.bold, color: PdfColors.blue900)),
          pw.SizedBox(height: 8),
          pw.TableHelper.fromTextArray(
            border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.5),
            headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 9, color: PdfColors.white),
            headerDecoration: const pw.BoxDecoration(color: PdfColors.indigo900),
            headers: ['Consistency Domain', 'Achieved Score Ratio (%)'],
            data: [
              ['Study Goals Compliance', '${scoreModel.studyConsistencyPercent}%'],
              ['Gym Attendance Compliance', '${scoreModel.gymConsistencyPercent}%'],
              ['Goal Success Rate', '${scoreModel.goalCompletionPercent}%'],
              ['Discipline & Streaks', '${scoreModel.streakConsistencyPercent}%'],
              ['Overall Rating Impact', '${scoreModel.overallConsistencyPercent}%'],
            ],
          ),

          pw.SizedBox(height: 20),

          // Productivity Insights Section
          pw.Text('3. Automated Productivity Insights', style: pw.TextStyle(fontSize: 13, fontWeight: pw.FontWeight.bold, color: PdfColors.blue900)),
          pw.SizedBox(height: 8),
          if (data.insights.isEmpty)
            pw.Text('No insights logged for this period.', style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600))
          else
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: data.insights.map((insight) {
                return pw.Container(
                  margin: const pw.EdgeInsets.only(bottom: 6),
                  padding: const pw.EdgeInsets.all(8),
                  decoration: pw.BoxDecoration(
                    color: PdfColors.grey100,
                    border: pw.Border.all(color: PdfColors.grey300, width: 0.5),
                    borderRadius: pw.BorderRadius.circular(4),
                  ),
                  child: pw.Row(
                    children: [
                      pw.Text('• ', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, color: PdfColors.blue800)),
                      pw.Expanded(
                        child: pw.Column(
                          crossAxisAlignment: pw.CrossAxisAlignment.start,
                          children: [
                            pw.Text(insight.title, style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 9)),
                            pw.Text(insight.message, style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey800)),
                          ],
                        ),
                      ),
                    ],
                  ),
                );
              }).toList(),
            ),

          pw.SizedBox(height: 20),

          // Achievements Unlocked Section
          pw.Text('4. Unlocked Badges & Achievements', style: pw.TextStyle(fontSize: 13, fontWeight: pw.FontWeight.bold, color: PdfColors.blue900)),
          pw.SizedBox(height: 8),
          pw.TableHelper.fromTextArray(
            border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.5),
            headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 9, color: PdfColors.white),
            headerDecoration: const pw.BoxDecoration(color: PdfColors.teal800),
            headers: ['Badge Title', 'Category', 'Difficulty', 'Status'],
            data: achievements.map((a) {
              return [
                a.title,
                a.category.label,
                a.difficulty.label,
                a.isUnlocked ? 'UNLOCKED 🏆' : 'Locked (${a.progressPercent}%)',
              ];
            }).toList(),
          ),
        ],
      ),
    );

    final pdfBytes = await pdf.save();
    final fileName = 'PrepTracker_Report_${DateFormat('yyyyMMdd_HHmm').format(DateTime.now())}.pdf';
    await ExportService.downloadFile(pdfBytes, fileName, 'application/pdf');
  }
}
